### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by ashesh-0** [dlmbl/boot#2]
I think the notebook is in good shape except for few minor things which I list here. We can discuss them over a call if you have opinions. 
Below, I'm writing few phrases present in the notebook inside double quotes and giving my opinion on them. This way it should be easy to find them. 

1.  "Set your python kernel to 00-boot" should be removed.
2.  There should be an instruction on how to add data to google colab. I manually copied data into colab's temporary filesystem.
3. "Generate a new image that respects these conventions" (convention is that shape should be (1,H,W)). Notebook encourages to use np.transpose(). However, that has the side effect that the height and width are also swapped.  If the objective is to introduce np.transpose(), this should be mentioned/shown (just plot the transposed version and ask the user to see if the image is still the same). Otherwise, np.swapaxes should be used , ``` np.swapaxes(data[None],0,3)[...,0]```.
4. "Visualizing Segmentation Maps" does not work.  ```seg_map``` variable is never defned.
5. "try a kernel size of 10", In the markdown, it says kernel should be odd. So, this should be changed to 9.
6. Sobel filter can be made optional ? I remember having this discussion in the call about making things optional here. Everthing else seems super relevant.

**Comment by lmanan** [comment]
Thanks Ashesh! Very valuable feedback. 
Updated the jupyter notebook to be a colab  notebook now.

**Comment by rayanirban** [comment]
These issues were from 2023 edition and were addressed by @lmanan
