### ISSUE TITLE
2023 report

### ISSUE THREAD

**Issue by neptunes5thmoon** [dlmbl/boot#5]
Issues:
- broken links in notebook (numpy cheatsheet etc)

Checkpoint times:
- Checkpoint 1 discussion after 25 minutes
- Checkpoint 2 discussion after 20 minutes (10-15 minutes would have been enough)
- Checkpoint 3 rest of the time (~30 minutes) , discussion took ~25 minutes

**Comment by rayanirban** [comment]
The links were updated in the 2024 edition and the checkpoint times were noted
